[package]
name = "rust-async-patterns-examples"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
tokio = { version = "=1.53.1", features = ["rt", "sync", "macros", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }

[dev-dependencies]
tokio = { version = "=1.53.1", features = ["test-util"] }
